import React from 'react'
import { headingStyle } from '../assets/styles'

function Revenue() {
    const points = [
        {
            heading: "User Engagement",
            content: "Engage with our platform by utilizing the various features such as text-to-text generation, text-to-image generation, text-to-video creation, and text-to-website development. The more you utilize and contribute to FuturAI, the greater your earning potential."
        },
        {
            heading: "Ad Revenue",
            content: "FuturAI generates revenue through targeted advertisements displayed on our platform. As a valued user, you will be eligible to earn a share of the ad revenue based on your level of activity and engagement. The more active you are, the more you can earn."
        },
        {
            heading: "Revenue Allocation",
            content: "Our revenue sharing plan allocates a percentage of the ad revenue generated by FuturAI to our users. The allocation is based on a tiered system, where users who contribute the most and have the highest engagement levels will receive a larger share of the revenue."
        },
        {
            heading: "Tiered System",
            content: "We have designed a tiered system to reward users based on their level of engagement. The tiers are determined by factors such as the number of interactions, content quality, and overall contribution to the FuturAI community. The higher your tier, the greater your share of the revenue."
        },
        {
            heading: "Payment Process",
            content: "Payments will be made on a regular basis, typically monthly, directly to your designated payment account. We support a variety of payment methods to ensure convenience and accessibility for our users."
        },
        {
            heading: "Transparency and Reporting",
            content: "We are committed to maintaining transparency in our revenue sharing program. You will have access to a personalized dashboard where you can track your earnings, view detailed reports, and monitor your progress within the tiered system."
        },
        {
            heading: "Community Support and Growth",
            content: "As our user base grows and the revenue generated by FuturAI increases, so does the earning potential for our users. We strive to continuously improve and expand our platform, providing more opportunities for you to earn and succeed."
        },
        {
            heading: "Join us at FuturAI",
            content: "Join us at FuturAI and become an active part of our community while earning from your engagement. Harness the power of our innovative features, contribute your knowledge and creativity, and be rewarded for your efforts. Embrace the future of revenue sharing with FuturAI today!"
        }
    ];
    return (
        <div id='revenue' className='flex flex-col w-full min-h-screen bg-gradient-to-r from-[#6959F7] to-[#13075E] px-4 items-center justify-center md:px-12 lg:px-24 py-8'>
            <div className='flex flex-col items-center justify-center w-full'>
                <h1 className={`${headingStyle} text-white`}>Revenue</h1>
                <p className='text-text text-md text-center lg:w-3/5 mb-12 mt-6'>At FuturAI, we believe in fostering a collaborative community and rewarding our users for their contributions. That's why we have implemented a transparent and fair revenue sharing plan that allows you to earn from your engagement on our platform. Here's how it works:</p>
                <div className="flex flex-wrap lg:-mx-4">
                    {points.map((point, index) => (
                        <div
                            key={index}
                            className="my-1 px-1 w-full md:w-1/2 lg:my-4 lg:px-4 lg:w-1/2"
                        >
                            <article className="overflow-hidden bg-white/10 border border-white/20 rounded-lg p-2 text-white">
                                <header className="flex items-center justify-between leading-tight p-2 md:p-4">
                                    <h1 className="text-xl font-bold uppercase tracking-wider">
                                        {point.heading}
                                    </h1>
                                </header>
                                <footer className="flex items-center justify-between leading-none p-2 md:p-4">
                                    <p className="text-md leading-normal">
                                        {point.content}
                                    </p>
                                </footer>
                            </article>
                        </div>
                    ))}
                </div>
            </div>
        </div>
    )
}

export default Revenue